#!/usr/bin/env bash

source .env

if [ $1 = "on" ]; then
  ADDR=$(curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"https:..([^"]*).*/\1/p')
  # curl -X POST https://api.telegram.org/bot${TOKEN}/setWebhook?${ADDR}
  # curl -F "url=https://"${ADDR} https://api.telegram.org/bot${TOKEN}/setWebhook

  echo "BOT_URL=https://"${ADDR} >.boturl
  echo ""
  echo "Bot Webhook Set @ ${ADDR}"
else
  curl https://api.telegram.org/bot${TOKEN}/deleteWebhook
  echo ""
  echo "Bot Webhook Deleted"
fi
